import { formatGeneratedAt, formatReportDateRange } from '../../utils/reportFormatter';
import { ORG_NAME } from '../../utils/orgInfo';

// title: report title, templateLabel: e.g. "Executive Summary",
// generatedAt: Date, generatedBy: string (user's full name),
// dateFrom/dateTo: optional active date-range filter, shown on the cover so
// a reader knows exactly what window this report covers.
export default function ReportCover({ title, templateLabel, generatedAt, generatedBy, dateFrom, dateTo }) {
  return (
    <div className="flex min-h-[70vh] flex-col justify-between break-after-page py-12 print:min-h-[90vh]">
      <div>
        <div className="mb-2 flex h-10 w-10 items-center justify-center rounded-xl bg-brass-500 font-display text-sm font-bold text-white">
          FR
        </div>
        <p className="mt-8 text-sm uppercase tracking-widest text-slate-400">{ORG_NAME}</p>
        <h2 id="report-cover-title" className="mt-2 font-display text-4xl font-semibold text-ink dark:text-slate-100">{title}</h2>
        <p className="mt-2 text-lg text-slate-500">{templateLabel}</p>
        <p className="mt-1 text-sm text-slate-400">Coverage: {formatReportDateRange(dateFrom, dateTo)}</p>
      </div>

      <dl className="grid grid-cols-2 gap-4 border-t border-slate-200 pt-6 text-sm dark:border-slate-700">
        <div>
          <dt className="text-xs uppercase tracking-wide text-slate-400">Generated</dt>
          <dd className="font-id text-slate-700 dark:text-slate-200">{formatGeneratedAt(generatedAt)}</dd>
        </div>
        <div>
          <dt className="text-xs uppercase tracking-wide text-slate-400">Generated By</dt>
          <dd className="text-slate-700 dark:text-slate-200">{generatedBy || 'Unknown user'}</dd>
        </div>
      </dl>
    </div>
  );
}
